import configureStore from '../../app/javascript/state';

const champaign = {
  page: {
    id: 2,
    language_id: 1,
    campaign_id: null,
    title: 'Petition',
    slug: 'petition',
    status: 'pending',
    action_count: 1,
    follow_up_page_id: 1,
    publish_status: 'published',
    allow_duplicate_actions: false,
    enforce_styles: false,
    publish_actions: 'secure',
    total_donations: '0.0',
    fundraising_goal: '100000.0',
    language_code: 'en',
    layout: 'Example Layout',
    follow_up_layout: null,
    plugins: ['Plugins::Fundraiser', 'Plugins::DonationsThermometer'],
  },
  personalization: {
    outstandingFields: [],
    paymentMethods: [],
    donationBands: {
      USD: [1, 5, 10, 15, 20],
      GBP: [1, 4, 7, 11, 14],
      EUR: [1, 4, 8, 12, 16],
      CHF: [1, 5, 10, 14, 19],
      AUD: [1, 7, 13, 20, 25],
      NZD: [1, 7, 14, 20, 30],
      CAD: [1, 6, 13, 19, 25],
    },
    donationsThermometer: {
      id: 1,
      title: null,
      offset: 10000,
      active: true,
      type: 'DonationsThermometer',
      percentage: 0,
      remaining_amounts: {
        USD: -90000,
        GBP: -90000,
        EUR: -90000,
        CHF: -90000,
        AUD: -90000,
        NZD: -90000,
        CAD: -90000,
      },
      total_donations: {
        USD: 10000,
        GBP: 10000,
        EUR: 10000,
        CHF: 10000,
        AUD: 10000,
        NZD: 10000,
        CAD: 10000,
      },
      goals: {
        USD: 100000,
        GBP: 100000,
        EUR: 100000,
        CHF: 100000,
        AUD: 100000,
        NZD: 100000,
        CAD: 100000,
      },
    },
    formValues: {
      name: 'Test USer',
      action_phone_number: '',
      email: 'test@example.com',
      country: 'US',
      postal: '10000',
    },
    location: {
      country_name: 'United States',
      country_code: 'US',
      currency: 'USD',
      country: 'US',
    },
    member: {
      id: 1,
      name: 'Test User',
      email: 'test@example.com',
      country: 'US',
      first_name: 'Test',
      last_name: 'User',
      postal: null,
      actionkit_user_id: null,
      donor_status: 'nondonor',
      consented: null,
      registered: false,
      full_name: 'Test User',
      welcome_name: 'Test User',
    },
  },
};

const store = configureStore(champaign);

export { store, champaign };
