extends:
  - airbnb-base
  - eslint-config-airbnb-base/rules/strict
env:
  browser: true
  commonjs: true
globals:
  I18n: I18n
  $: $
  Backbone: Backbone
  _: _
  slugChecker: SlugChecker

rules:
  no-fallthrough: 0
