inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/IndentationConsistency:
  EnforcedStyle: normal

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Lint/BlockAlignment:
  AlignWith: start_of_block

Lint/InheritException:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  MaxLineLength: 40

Lint/HandleExceptions:
  Enabled: false

