inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'

Style/ModuleFunction:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Lint/InheritException:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
