// flow-typed signature: 8237acc363999edb42c21f5b680eb86a
// flow-typed version: <<STUB>>/draft-js_v0.10.5/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js' {
  declare module.exports: any;
}
