// flow-typed signature: 372ee5719578e50a21438aeb7ff7d5a1
// flow-typed version: <<STUB>>/flat_v4/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flat' {
  declare type FlatObject = {
    [key: string]: boolean | string | number | void | Function | Array<boolean | string | number | void | Function>
  };

  declare type FlattenOptions = {
    delimiter?: string,
    safe?: boolean,
    object?: boolean,
    overwrite?: boolean,
    maxDepth?: number,
  }

  declare interface Flatten {
    <T>(input: T): FlatObject;
    flatten: <T>(input: T, options?: FlattenOptions) => FlatObject;
    unflatten: <T>(input: T, options?: FlattenOptions) => Object;
  }

  declare module.exports: Flatten;
}
