// flow-typed signature: 02094ad5982e808abc44ba93ff66a4ba
// flow-typed version: <<STUB>>/react-intl_v^2.1.5/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl' {

  /*

    S = State
    A = Action
    OP = OwnProps
    SP = StateProps
    DP = DispatchProps

  */

  declare module.exports: any;

  declare type NumberFormatOptions = {
    localeMatcher: 'best fit' | 'lookup';
    style: 'decimal' | 'currency' | 'percent';
    currency: string;
    currencyDisplay: 'symbol' | 'code' | 'name';
    useGrouping: boolean;
    minimumIntegerDigits: number;
    minimumFractionDigits: number;
    maximumFractionDigits: number;
    minimumSignificantDigits: number;
    maximumSignificantDigits: number;
  };

  declare type IntlProps = {
    formatNumber(value: any, options?: NumberFormatOptions): string;
  };
}
