// flow-typed signature: 12a295b440902395cdfb38e465210cd8
// flow-typed version: <<STUB>>/sou-assets_vgit://github.com/SumOfUs/sou-assets.git#npm

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sou-assets'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sou-assets' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sou-assets/javascripts/backbone/action_counter' {
  declare module.exports: any;
}

declare module 'sou-assets/javascripts/backbone/desktop_sticky' {
  declare module.exports: any;
}

declare module 'sou-assets/javascripts/backbone/simple_carousel' {
  declare module.exports: any;
}

declare module 'sou-assets/javascripts/champaign' {
  declare module.exports: any;
}

declare module 'sou-assets/javascripts/check_top' {
  declare module.exports: any;
}

declare module 'sou-assets/javascripts/ga_event_reporting' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sou-assets/javascripts/backbone/action_counter.js' {
  declare module.exports: $Exports<'sou-assets/javascripts/backbone/action_counter'>;
}
declare module 'sou-assets/javascripts/backbone/desktop_sticky.js' {
  declare module.exports: $Exports<'sou-assets/javascripts/backbone/desktop_sticky'>;
}
declare module 'sou-assets/javascripts/backbone/simple_carousel.js' {
  declare module.exports: $Exports<'sou-assets/javascripts/backbone/simple_carousel'>;
}
declare module 'sou-assets/javascripts/champaign.js' {
  declare module.exports: $Exports<'sou-assets/javascripts/champaign'>;
}
declare module 'sou-assets/javascripts/check_top.js' {
  declare module.exports: $Exports<'sou-assets/javascripts/check_top'>;
}
declare module 'sou-assets/javascripts/ga_event_reporting.js' {
  declare module.exports: $Exports<'sou-assets/javascripts/ga_event_reporting'>;
}
