option_settings:
  - namespace:  aws:elasticbeanstalk:application:environment
    option_name: RSA_PRIVATE
    value: $RSA_PRIVATE
  - namespace:  aws:elasticbeanstalk:application:environment
    option_name: SSL_CERTIFICATE
    value: $SSL_CERTIFICATE
