// flow-typed signature: c93dd3dd98b98a974a7d519a681da7ab
// flow-typed version: <<STUB>>/braintree-web_v^3.5.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'braintree-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'braintree-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'braintree-web/american-express.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/american-express' {
  declare module.exports: any;
}

declare module 'braintree-web/apple-pay.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/apple-pay' {
  declare module.exports: any;
}

declare module 'braintree-web/client.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/client' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/data-collector' {
  declare module.exports: any;
}

declare module 'braintree-web/debug' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/hosted-fields' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/paypal' {
  declare module.exports: any;
}

declare module 'braintree-web/three-d-secure.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/three-d-secure' {
  declare module.exports: any;
}

declare module 'braintree-web/unionpay.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/unionpay' {
  declare module.exports: any;
}

declare module 'braintree-web/us-bank-account.debug' {
  declare module.exports: any;
}

declare module 'braintree-web/us-bank-account' {
  declare module.exports: any;
}

// Filename aliases
declare module 'braintree-web/american-express.debug.js' {
  declare module.exports: $Exports<'braintree-web/american-express.debug'>;
}
declare module 'braintree-web/american-express.js' {
  declare module.exports: $Exports<'braintree-web/american-express'>;
}
declare module 'braintree-web/apple-pay.debug.js' {
  declare module.exports: $Exports<'braintree-web/apple-pay.debug'>;
}
declare module 'braintree-web/apple-pay.js' {
  declare module.exports: $Exports<'braintree-web/apple-pay'>;
}
declare module 'braintree-web/client.debug.js' {
  declare module.exports: $Exports<'braintree-web/client.debug'>;
}
declare module 'braintree-web/client.js' {
  declare module.exports: $Exports<'braintree-web/client'>;
}
declare module 'braintree-web/data-collector.debug.js' {
  declare module.exports: $Exports<'braintree-web/data-collector.debug'>;
}
declare module 'braintree-web/data-collector.js' {
  declare module.exports: $Exports<'braintree-web/data-collector'>;
}
declare module 'braintree-web/debug.js' {
  declare module.exports: $Exports<'braintree-web/debug'>;
}
declare module 'braintree-web/hosted-fields.debug.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields.debug'>;
}
declare module 'braintree-web/hosted-fields.js' {
  declare module.exports: $Exports<'braintree-web/hosted-fields'>;
}
declare module 'braintree-web/index' {
  declare module.exports: $Exports<'braintree-web'>;
}
declare module 'braintree-web/index.js' {
  declare module.exports: $Exports<'braintree-web'>;
}
declare module 'braintree-web/paypal.debug.js' {
  declare module.exports: $Exports<'braintree-web/paypal.debug'>;
}
declare module 'braintree-web/paypal.js' {
  declare module.exports: $Exports<'braintree-web/paypal'>;
}
declare module 'braintree-web/three-d-secure.debug.js' {
  declare module.exports: $Exports<'braintree-web/three-d-secure.debug'>;
}
declare module 'braintree-web/three-d-secure.js' {
  declare module.exports: $Exports<'braintree-web/three-d-secure'>;
}
declare module 'braintree-web/unionpay.debug.js' {
  declare module.exports: $Exports<'braintree-web/unionpay.debug'>;
}
declare module 'braintree-web/unionpay.js' {
  declare module.exports: $Exports<'braintree-web/unionpay'>;
}
declare module 'braintree-web/us-bank-account.debug.js' {
  declare module.exports: $Exports<'braintree-web/us-bank-account.debug'>;
}
declare module 'braintree-web/us-bank-account.js' {
  declare module.exports: $Exports<'braintree-web/us-bank-account'>;
}
