defaults: &defaults
  secret_key_base:        <%= Settings.secret_key_base %>
  omniauth_client_secret: 'BvwkosOPs2JywGFnxKNxkCew'
  omniauth_client_id:     '296467595055-j0gjmnfe53dkjgr50c69h8kbvg354c8n.apps.googleusercontent.com'
  devise_secret_key:      <%= Settings.devise_secret_key %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
