defaults: &defaults
  secret_key_base:        <%= ENV['SECRET_KEY_BASE'] %>
  omniauth_client_secret: <%= ENV['OMNIAUTH_CLIENT_SECRET'] %>
  omniauth_client_id:     <%= ENV['OMNIAUTH_CLIENT_ID'] %>
  devise_secret_key:      <%= ENV['DEVISE_SECRET_KEY'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
