defaults: &defaults
  secret_key_base:        <%= Settings.secret_key_base %>
  omniauth_client_secret: <%= ENV['OMNIAUTH_CLIENT_SECRET'] %>
  omniauth_client_id:     <%= ENV['OMNIAUTH_CLIENT_ID'] %>
  devise_secret_key:      <%= Settings.devise_secret_key %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
