defaults: &defaults
  secret_key_base:        <%= Settings.secret_key_base %>
  omniauth_client_secret: <%= Settings.omniauth_client_secret %>
  omniauth_client_id:     <%= Settings.omniauth_client_id %>
  devise_secret_key:      <%= Settings.devise_secret_key %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
