module PaymentProcessor
  module Clients
    module Braintree
      class ErrorProcessing

        # Collection of error codes, generated by braintree for invalid
        # customer/credit card transaction data.
        #
        # See https://developers.braintreepayments.com/reference/general/validation-errors/all/ruby
        # for code definitions.
        #
        USER_ERROR_CODES = [
          (81801..81813),
          (81501..81503),
          (91814..91826),
          (81604..81608),
          (81613..81616),
          (81709..81717),
          (91723..91726),
          81827,
          91803,
          81601,
          81723,
          81703,
          81706,
          81707,
          81736,
          81737,
          81528,
          81509].map{|code| code.is_a?(Range) ? code.to_a : code }
                .flatten
                .freeze

        FILTER = -> (error) { USER_ERROR_CODES.include?( error.code.to_i ) }

        def initialize(response)
          @response = response
        end

        def process
          if user_errors.any?
            return user_errors
          else
            raise_system_errors if system_errors.any?
          end
        end

        private

        def raise_system_errors
          raise ::Braintree::ValidationsFailed.new(error_messages)
        end

        def error_messages
          system_errors.map{|e| "#{e.message} (#{e.code} on #{e.attribute})"}.join(', ')
        end

        def user_errors
          @user_errors ||= errors.select(&FILTER)
        end

        def system_errors
          @system_errors ||= errors.reject(&FILTER)
        end

        def errors
          @response.errors
        end
      end
    end
  end
end

