web:
  image: soutech/champaign_web:$CIRCLE_SHA1
  links:
    - db
    - redis
  command: /champaign/circle/specs-and-rake-tasks
  env_file:
    - test.env

db:
  image: postgres
  ports:
    - "5432"
  environment:
    POSTGRES_DB: champaign_test

redis:
  image: redis
