#!/bin/bash
set -eu -o pipefail

cd "$(dirname $0)/.."

host="$CIRCLE_DB_1_PORT_5432_TCP_ADDR"
port="$CIRCLE_DB_1_PORT_5432_TCP_PORT"

export PG_HOST="$host"
export PG_USERNAME="postgres"
export PG_PORT="$port"

echo -n "waiting for TCP connection to $host:$port"

# Tries to connect to the DB and sleeps until it can
while ! nc -w 1 $host $port 2>/dev/null
do
    echo -n "."
    sleep 1
done

echo "OK"

# Then it runs tests
rspec spec

# And then it tries to run all of the rake tasks
bundle exec rake db:migrate db:seed champaign:seed_liquid

# Try to precompile assets with production mode
bundle exec rake RAILS_ENV=production assets:precompile