#!/bin/bash
set -eu -o pipefail

cd "$(dirname $0)/.."

host="$CIRCLE_DB_1_PORT_5432_TCP_ADDR"
port="$CIRCLE_DB_1_PORT_5432_TCP_PORT"

export PG_HOST="$host"
export PG_USERNAME="postgres"
export PG_PORT="$port"

echo -n "waiting for TCP connection to $host:$port"

# Tries to connect to the DB and sleeps until it can
while ! nc -w 1 $host $port 2>/dev/null
do
    echo -n "."
    sleep 1
done

echo "OK"

# Lint codebase 
bundle exec rubocop

# Runs tests
bundle exec rspec spec
npm run test

# Try to run all of the DB-related rake tasks
bundle exec rake RAILS_ENV=test db:migrate db:seed champaign:seed_liquid
